version: '3.4'

services:
  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: CatalogApi/Dockerfile

  catalogdb:
    image: mongo

  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: BasketApi/Dockerfile

  basketdb:
    image: redis:alpine

volumes:
  mongo_data:

