version: '3.4'

services:
  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: CatalogApi/Dockerfile

  catalogdb:
    image: mongo

  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: BasketApi/Dockerfile

  basketdb:
    image: redis:alpine

  inventorygrpc:
    image: ${DOCKER_REGISTRY-}inventorygrpc
    build:
      context: .
      dockerfile: InventoryGrpc/Dockerfile
 
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

volumes:
  mongo_data:


